:bug: Remove defaults from crd v1beta1
kubernetes-sigs/controller-tools pull request #446
Opened 2020-05-25 19:29 UTC by tamalsaha

Fixes https://github.com/kubernetes-sigs/controller-tools/issues/445

Signed-off-by: Tamal Saha <tamal@appscode.com>

2020-08-19 15:11 UTC, vincepri commented
It seems a little strange to me that we'd silently remove the defaults markers for an unsupported type, this could lead into confusion, thoughts @alvaroaleman @DirectXMan12 ?

2020-09-10 00:19 UTC, DirectXMan12 requested changes
left comment, needs a test case, also we should probably warn about this, or maybe just error out.
I'd lean towards just erroring out, but I wouldn't be surprised if people have workarounds (deploying different controller versions or webhooks but same YAML), so a warning is probably better.

2020-09-10 00:19 UTC, DirectXMan12 commented on pkg/crd/gen.go
> +func removeDefaults(schema *apiextlegacy.JSONSchemaProps) {
we've got a schema visitor for this purpose, so you shouldn't have to manually write a schema visitor.

2020-09-15 06:41 UTC, DirectXMan12 commented
Closed by #481, but that'll need some fixups.

2020-09-18 09:16 UTC, closed without merging